// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Add-0]
	_ = x[Sub-1]
	_ = x[Mul-2]
	_ = x[Div-3]
	_ = x[Mod-4]
	_ = x[Equal-5]
	_ = x[Equals-6]
	_ = x[NotEq-7]
	_ = x[Less-8]
	_ = x[LessEq-9]
	_ = x[Greater-10]
	_ = x[GreaterEq-11]
	_ = x[Glue-12]
	_ = x[Declare-13]
	_ = x[Branch-14]
	_ = x[While-15]
	_ = x[Function-16]
	_ = x[Parameter-17]
	_ = x[Identifier-18]
	_ = x[Sycall-19]
	_ = x[Call-20]
	_ = x[Implicit-21]
	_ = x[Literal-22]
	_ = x[Invalid-23]
}

const _Kind_name = "AddSubMulDivModEqualEqualsNotEqLessLessEqGreaterGreaterEqGlueDeclareBranchWhileFunctionParameterIdentifierSycallCallImplicitLiteralInvalid"

var _Kind_index = [...]uint8{0, 3, 6, 9, 12, 15, 20, 26, 31, 35, 41, 48, 57, 61, 68, 74, 79, 87, 96, 106, 112, 116, 124, 131, 138}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
