// Code generated by "stringer -type=Type"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Byte-0]
	_ = x[Short-1]
	_ = x[Int-2]
	_ = x[Long-3]
	_ = x[UByte-4]
	_ = x[UShort-5]
	_ = x[UInt-6]
	_ = x[ULong-7]
	_ = x[PtrInt-8]
	_ = x[Float-9]
	_ = x[Double-10]
	_ = x[String-11]
	_ = x[None-12]
}

const _Type_name = "ByteShortIntLongUByteUShortUIntULongPtrIntFloatDoubleStringNone"

var _Type_index = [...]uint8{0, 4, 9, 12, 16, 21, 27, 31, 36, 42, 47, 53, 59, 63}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
